apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.secretName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.externalDatabase.url | b64enc | quote }}
  {{- end }}
