{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "portable.fullname" . }}-tls
  labels:
    {{- include "portable.labels" . | nindent 4 }}
spec:
  secretName: {{ include "portable.fullname" . }}-tls
  issuerRef:
    name: {{ .Values.certManager.issuer }}
    kind: {{ .Values.certManager.issuerKind }}
  dnsNames:
    - {{ .Values.domain | quote }}
    - {{ printf "*.%s" .Values.domain | quote }}
{{- end }}
