apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portable.secretName" . }}
  labels:
    {{- include "portable.labels" . | nindent 4 }}
type: Opaque
data:
  github-client-id: {{ .Values.github.clientId | b64enc | quote }}
  github-client-secret: {{ .Values.github.clientSecret | b64enc | quote }}
  {{- if .Values.postgres.enabled }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  {{- end }}
  encryption-key: {{ .Values.encryptionKey | b64enc | quote }}
